version: '3'
services:
  mysql:
    image: mysql:5.7
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
    ports:
      - 3307:3306
    container_name: nodejs-mysql
  node-app:
    depends_on:
      - mysql
    build: .
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DB_HOST=localhost
      - DB_USER=root
      - DB_PASSWORD=pass123
      - DB_NAME=Test_db
      - DB_PORT=3307
  